version: '3'
services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"